Build go-webrtc and snowflake for mac.
tor-browser-bundle.git author: David Fifield <david@bamsoftware.com>
tor-browser-bundle.git commit: 26e0cd44f2886bfad1c3d30844ff7a21eb9d0478

Commit message from the tor-browser-bundle.git commit:

Build go-webrtc and snowflake in the mac pluggable-transports descriptor.

I had to apply two tricks to get a reproducible snowflake-client.

The first is to use faketime to eliminate some timestamps. There were 11
variable timestamps in the file. Through experimentation, I found that
10 of them were dependent on the Go runtime (recompiling Go caused them
to change) and 1 was dependent on snowflake-client itself (recompiling
snowflake-client with the same runtime changed only that 1 timestamp).
The underlying issue has to do with clang 3.8.0 on Darwin embedding
timestamps, unsolved in the Go issue tracker as of 13 days ago.
https://github.com/golang/go/issues/9206#issuecomment-310476743

The second is a sed command to clobber embedded paths of the form
/tmp/go-buildXXXXXXXXX and /tmp/go-link-XXXXXXXXX. Their presence is
caused by some combination of Clang and Darwin, and there is as yet no
known workaround upstream.

diff --git a/projects/snowflake/build b/projects/snowflake/build
--- a/projects/snowflake/build
+++ b/projects/snowflake/build
@@ -10,6 +10,12 @@ distdir=/var/tmp/dist/[% project %]
 [% IF c("var/osx") %]
   PTDIR="$distdir/Contents/MacOS/Tor/PluggableTransports"
   DOCSDIR="$distdir/Contents/Resources/TorBrowser/Docs/snowflake"
+  export CGO_ENABLED=1
+  export CGO_CFLAGS="[% c("var/FLAGS") %] -mmacosx-version-min=10.7"
+  export CGO_CXXFLAGS="[% c("var/FLAGS") %] -stdlib=libc++ -mmacosx-version-min=10.7"
+  export CGO_LDFLAGS="[% c("var/FLAGS") %] -stdlib=libc++ -mmacosx-version-min=10.7"
+  export CC="$clangdir/bin/clang"
+  export CXX="$clangdir/bin/clang++"
 [% ELSE %]
   PTDIR="$distdir/TorBrowser/Tor/PluggableTransports"
   DOCSDIR="$distdir/TorBrowser/Docs/snowflake"
@@ -25,7 +31,35 @@ tar -C /var/tmp/build -xf [% project %]-[% c('version') %].tar.gz
 cd /var/tmp/build/[% project %]-[% c('version') %]
 
 cd client
-go build -ldflags '-s'
+[% IF c("var/osx") -%]
+  # Without faketime, snowflake-client would contain the timestamp of the
+  # temporary client.a file created during "go build".
+  [% c("var/faketime") %] go build -ldflags '-s'
+[% ELSE -%]
+  go build -ldflags '-s'
+[% END -%]
+[% IF c("var/osx") -%]
+  # Hack: Overwrite variable absolute paths embedded in the binary. clang 3.8.0
+  # on Darwin embeds such paths and the issue is unsolved in upstream Go as of
+  # 2016-06-28:
+  # https://github.com/golang/go/issues/9206#issuecomment-310476743
+  # The two kinds of paths are ("000000000" stands for 9 random digits):
+  #   /tmp/go-build000000000
+  #   /tmp/go-link-000000000
+  # Such paths are the output of ioutil.TempDir("", "go-build") and
+  # ioutil.TempDir("", "go-link-").
+  cp -a client client.stomped
+  sed -i -E -e 's#(/tmp/go-build|/tmp/go-link-)[0-9]{9}/#\1XXXXXXXXX/#g' client.stomped
+  # Sanity check: make sure the file actually changed. If it did not, it could
+  # mean that a change in go or clang has made this step unnecessary.
+  if cmp client client.stomped
+  then
+    echo "No paths replaced in snowflake-client. Maybe the replacement failed or is no longer needed."
+    echo "Check projects/snowflake/build"
+    exit 1
+  fi
+  mv -f client.stomped client
+[% END -%]
 cp -a client[% IF c("var/windows") %].exe[% END %] $PTDIR/snowflake-client[% IF c("var/windows") %].exe[% END %]
 
 cd ..
